AllCops:
  DisplayStyleGuide: true
# BlockNesting:
#   Max: 4
Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  MinSize: 8
# Layout/MultilineOperationIndentation:
#   Enabled: false
Metrics/AbcSize:
  Max: 65
Metrics/BlockLength:
  Max: 100
Metrics/MethodLength:
  Max: 65
# Metrics/ClassLength:
#   Max: 300
#   Enabled: false
Metrics/LineLength:
  Max: 175
# Metrics/PerceivedComplexity:
#   Max: 11
#   Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
#   Enabled: false
# #Style/Tab:
#   #Enabled: false
# Style/Next:
#   Enabled: false
# Style/BracesAroundHashParameters:
#   Enabled: false
# Style/ParenthesesAroundCondition:
#   Enabled: false
# Style/PredicateName:
#   Enabled: false
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/FrozenStringLiteralComment:
  Enabled: false
