development:
  adapter: sqlite3
  database: <%=Rails.root + 'db/development.sqlite3'%>

test:
  adapter: sqlite3
  database: <%=Rails.root + 'db/test.sqlite3'%>

production:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 10 %>
  database: highline_production
  username: highline
  password: <%=ENV['DB_PASSWORD']%>